export class CryptoLogicImages {
clNavbarLogo="assets/logo.png";
clNavbarLogoWhite="assets/logoWhite.png";
clDashboardFirstImage='assets/dashboard1.png';
clDashboardButton ='assets/Button.png';
clDashboardNewsFirst='assets/news1.png';
clDashboardNewsSecond='assets/news2.png';
clDashboardNewsThird='assets/news3.png';
clDashboardNewsForuth='assets/news4.png';
clDashboardNewsFifth='assets/news5.png';
clDashboardOpinionUser1='assets/user1.png';
clDashboardOpinionUser2='assets/user2.png';
clDashboardOpinionUser3='assets/user3.png';
clDashboardOpinionUser4='assets/user4.png';
clDashboardOpinionUser5='assets/user5.png';
clCryptoFirstImage='assets/crypto1.png';
clCryptoDescriptionImage='assets/crypto2.png';
clCryptoRanking1='assets/btc.png';
clCryptoRanking2='assets/eth.png';
clCryptoRanking3='assets/bnb.png';
clCryptoRanking4='assets/ripple.png';
clCryptoRanking5='assets/cardano.png';
clBlockchainFirstImage='assets/blockchain1.png'
clBlockchainDescriptionImage='assets/blockchain2.png'
clInvestFirstImage='assets/invest1.png'
clInvestDescriptionImage='assets/invest2.png'
clCryptoMinersFirstImage='assets/cryptominers1.png'
clCryptoMinersDescriptionImage='assets/cryptominers2.png'
clFooterInsta = 'assets/insta.png'
clFooterFacebook = 'assets/facebook.png'
clFooterGithub = 'assets/github.png'
clFooterTwitter = 'assets/twitter.png'
}
